name: CI Pipeline & Docker Build (Advance)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn xgboost joblib matplotlib seaborn

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Jalankan MLflow Project & Build Docker
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: |
        # 1. Masuk ke folder MLProject dulu (PENTING!)
        echo "Masuk ke folder project..."
        cd MLProject
        
        # 2. Jalankan Training Langsung
        # Sekarang pasti bisa, karena modelling.py ada di sebelah kita
        echo "Menjalankan script training..."
        python modelling.py --n_estimators 100 --learning_rate 0.1
        
        # Cek apakah folder lokal berhasil dibuat
        echo "Mengecek folder model lokal..."
        ls -R model_docker_local
        
        # 3. Build Docker Image dari Folder LOKAL
        # Karena kita masih di dalam folder MLProject, path-nya ./model_docker_local
        IMAGE_NAME="${DOCKER_USER}/telco-churn-model:v1"
        
        echo "Sedang membuild Docker Image dari LOKAL: $IMAGE_NAME ..."
        
        mlflow models build-docker --model-uri "./model_docker_local" --name "$IMAGE_NAME"
        
        # 4. Upload ke Docker Hub
        echo "Mengupload ke Docker Hub..."
        docker push "$IMAGE_NAME"
